### ISSUE TITLE
[Feature]: Keda Azure Key Vault Secret

### ISSUE THREAD

**Issue by cedrichelloasso** [clemlesne/blue-agent#348]
### Feature

Is it possible to implement this keda feature (https://keda.sh/docs/2.16/authentication-providers/azure-key-vault/)? 
I don't want to clear the PAT, and if we use SecretProviderClass for Azure Key Vault, there is a bug (https://github.com/kedacore/keda/issues/2315)
It would be interesting to use this feature, what do you think?

Thank you,

### Use case

With the SecretProviderClass, We have this error:
KEDA won't scale when Secret is created by Secrets Store CSI Driver

**Comment by cedrichelloasso** [comment]
for clarification, I'm talking about this:

```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "blue-agent.fullname" . }}
  labels:
    {{- include "blue-agent.labels" . | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: organizationURL
      name: {{ include "blue-agent.secretName" . }}
      key: organizationURL
    - parameter: personalAccessToken
      name: {{ include "blue-agent.secretName" . }}
      key: personalAccessToken
```

The goal is add azureKeyVault for example.

It's possible ?

**Comment by clemlesne** [comment]
That's a good point to secure the secrets.

Well, we need to keep in mind that the `personalAccessToken` and `organizationURL` fields are used both by the container to run/register and KEDA to fetch the job queue status. Thus, it should be preferable, in my opinion, to keep the same secret implementation for both.

There is already an option to disable the automatic secret creation with `.Values.secret.create`. Some are already this to manage the secrets lifecycle with Hashicorp Vault.

AKS already expose a plugin `azure-keyvault-secrets-provider` to manage the sync between Kubernetes secrets objects and Key Vault.

We could add a flag to automatically create the CRD, [with that model](https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-configuration-options#sync-mounted-content-with-a-kubernetes-secret):

```yaml
{{- if .Capabilities.APIVersions.Has "secrets-store.csi.x-k8s.io/v1" -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "blue-agent.fullname" . }}-azure-key-vault
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "blue-agent.secretName" . }}
      type: Opaque
      data:
        - key: personalAccessToken
          objectName: personal-access-token
        - key: organizationURL
          objectName: organization-url
{{- end }}
```

Would it fit your use-case?
