### ISSUE TITLE
[Question]: Initialize Job takes 2 minutes

### ISSUE THREAD

**Issue by coderveehan** [clemlesne/blue-agent#354]
Is there a recommended way to reduce the amount of time it takes for the "Initialize Job" task? I think it takes the longest to Download all required tasks

**Comment by clemlesne** [comment]
I understand you feel that task initialization takes too long.

- On what arch are you?
- How much time does it take to initialize?
- Did the time changed by the past? With what and how much?
- What is the system usage of your containers (cpu, ram, network)?
- What is the variability of that time?

**Comment by coderveehan** [comment]
os - `Ubuntu 22.04.5 LTS` 
arch - `x86_64`
resources  - 
```
resources:
  # Resource limits
  limits:
    cpu: 2
    ephemeral-storage: 4Gi
    memory: 4Gi
  # Resource requests
  requests:
    cpu: 1
    ephemeral-storage: 1Gi
    memory: 2Gi
```

It takes about 2-4 minutes to initialize. It never takes less than 2 minutes. Nothing has changed, it has always been like this since day 1. It specifically takes time to download tasks, so I am wondering if there is a way to persist the tasks?
